schema_version = "1.0.0"

id = "io_import_ps2_ico"
version = "1.0.0"
name = "PS2 Icon (.ico) importer"
tagline = "Importa iconos 3D (.ico) de PlayStation 2"
maintainer = "mostazaniikkkk"
type = "add-on"

tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
